<?php
/**
 * This defines autoloading handler for whole MediaWiki framework
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 * http://www.gnu.org/copyleft/gpl.html
 *
 * @file
 */

/**
 * Locations of core classes
 * Extension classes are specified with $wgAutoloadClasses
 * This array is a global instead of a static member of AutoLoader to work around a bug in APC
 */
global $wgAutoloadLocalClasses;

$wgAutoloadLocalClasses = array(
	# Includes
	'AjaxDispatcher' => __DIR__.'/AjaxDispatcher.php',
	'AjaxResponse' => __DIR__.'/AjaxResponse.php',
	'AlphabeticPager' => __DIR__.'/Pager.php',
	'Article' => __DIR__.'/Article.php',
	'AtomFeed' => __DIR__.'/Feed.php',
	'AuthPlugin' => __DIR__.'/AuthPlugin.php',
	'AuthPluginUser' => __DIR__.'/AuthPlugin.php',
	'Autopromote' => __DIR__.'/Autopromote.php',
	'BaseTemplate' => __DIR__.'/SkinTemplate.php',
	'Block' => __DIR__.'/Block.php',
	'CacheHelper' => __DIR__.'/CacheHelper.php',
	'Category' => __DIR__.'/Category.php',
	'Categoryfinder' => __DIR__.'/Categoryfinder.php',
	'CategoryPage' => __DIR__.'/CategoryPage.php',
	'CategoryViewer' => __DIR__.'/CategoryViewer.php',
	'ChangesFeed' => __DIR__.'/ChangesFeed.php',
	'ChangeTags' => __DIR__.'/ChangeTags.php',
	'ChannelFeed' => __DIR__.'/Feed.php',
	'Collation' => __DIR__.'/Collation.php',
	'CollationCkb' => __DIR__.'/Collation.php',
	'ConcatenatedGzipHistoryBlob' => __DIR__.'/HistoryBlob.php',
	'Cookie' => __DIR__.'/Cookie.php',
	'CookieJar' => __DIR__.'/Cookie.php',
	'CurlHttpRequest' => __DIR__.'/HttpFunctions.php',
	'DeprecatedGlobal' => __DIR__.'/DeprecatedGlobal.php',
	'DerivativeRequest' => __DIR__.'/WebRequest.php',
	'DiffHistoryBlob' => __DIR__.'/HistoryBlob.php',
	'DummyLinker' => __DIR__.'/Linker.php',
	'Dump7ZipOutput' => __DIR__.'/Export.php',
	'DumpBZip2Output' => __DIR__.'/Export.php',
	'DumpFileOutput' => __DIR__.'/Export.php',
	'DumpFilter' => __DIR__.'/Export.php',
	'DumpGZipOutput' => __DIR__.'/Export.php',
	'DumpLatestFilter' => __DIR__.'/Export.php',
	'DumpMultiWriter' => __DIR__.'/Export.php',
	'DumpNamespaceFilter' => __DIR__.'/Export.php',
	'DumpNotalkFilter' => __DIR__.'/Export.php',
	'DumpOutput' => __DIR__.'/Export.php',
	'DumpPipeOutput' => __DIR__.'/Export.php',
	'EditPage' => __DIR__.'/EditPage.php',
	'EmailNotification' => __DIR__.'/UserMailer.php',
	'FakeTitle' => __DIR__.'/FakeTitle.php',
	'Fallback' => __DIR__.'/Fallback.php',
	'FauxRequest' => __DIR__.'/WebRequest.php',
	'FauxResponse' => __DIR__.'/WebResponse.php',
	'FeedItem' => __DIR__.'/Feed.php',
	'FeedUtils' => __DIR__.'/FeedUtils.php',
	'FileDeleteForm' => __DIR__.'/FileDeleteForm.php',
	'ForkController' => __DIR__.'/ForkController.php',
	'FormOptions' => __DIR__.'/FormOptions.php',
	'GitInfo' => __DIR__.'/GitInfo.php',
	'HistoryBlob' => __DIR__.'/HistoryBlob.php',
	'HistoryBlobCurStub' => __DIR__.'/HistoryBlob.php',
	'HistoryBlobStub' => __DIR__.'/HistoryBlob.php',
	'Hooks' => __DIR__.'/Hooks.php',
	'Html' => __DIR__.'/Html.php',
	'HtmlFormatter' => __DIR__.'/HtmlFormatter.php',
	'HTMLApiField' => __DIR__.'/htmlform/HTMLApiField.php',
	'HTMLButtonField' => __DIR__.'/htmlform/HTMLButtonField.php',
	'HTMLCheckField' => __DIR__.'/htmlform/HTMLCheckField.php',
	'HTMLCheckMatrix' => __DIR__.'/htmlform/HTMLCheckMatrix.php',
	'HTMLEditTools' => __DIR__.'/htmlform/HTMLEditTools.php',
	'HTMLFloatField' => __DIR__.'/htmlform/HTMLFloatField.php',
	'HTMLForm' => __DIR__.'/htmlform/HTMLForm.php',
	'HTMLFormField' => __DIR__.'/htmlform/HTMLFormField.php',
	'HTMLFormFieldRequiredOptionsException' =>
		'includes/htmlform/HTMLFormFieldRequiredOptionsException.php',
	'HTMLHiddenField' => __DIR__.'/htmlform/HTMLHiddenField.php',
	'HTMLInfoField' => __DIR__.'/htmlform/HTMLInfoField.php',
	'HTMLIntField' => __DIR__.'/htmlform/HTMLIntField.php',
	'HTMLNestedFilterable' => __DIR__.'/htmlform/HTMLNestedFilterable.php',
	'HTMLMultiSelectField' => __DIR__.'/htmlform/HTMLMultiSelectField.php',
	'HTMLRadioField' => __DIR__.'/htmlform/HTMLRadioField.php',
	'HTMLSelectAndOtherField' => __DIR__.'/htmlform/HTMLSelectAndOtherField.php',
	'HTMLSelectField' => __DIR__.'/htmlform/HTMLSelectField.php',
	'HTMLSelectOrOtherField' => __DIR__.'/htmlform/HTMLSelectOrOtherField.php',
	'HTMLSubmitField' => __DIR__.'/htmlform/HTMLSubmitField.php',
	'HTMLTextAreaField' => __DIR__.'/htmlform/HTMLTextAreaField.php',
	'HTMLTextField' => __DIR__.'/htmlform/HTMLTextField.php',
	'Http' => __DIR__.'/HttpFunctions.php',
	'ICacheHelper' => __DIR__.'/CacheHelper.php',
	'IcuCollation' => __DIR__.'/Collation.php',
	'IdentityCollation' => __DIR__.'/Collation.php',
	'ImageHistoryList' => __DIR__.'/ImagePage.php',
	'ImageHistoryPseudoPager' => __DIR__.'/ImagePage.php',
	'ImagePage' => __DIR__.'/ImagePage.php',
	'ImageQueryPage' => __DIR__.'/ImageQueryPage.php',
	'ImportStreamSource' => __DIR__.'/Import.php',
	'ImportStringSource' => __DIR__.'/Import.php',
	'IndexPager' => __DIR__.'/Pager.php',
	'Interwiki' => __DIR__.'/interwiki/Interwiki.php',
	'LCStore' => __DIR__.'/cache/LocalisationCache.php',
	'LCStoreAccel' => __DIR__.'/cache/LocalisationCache.php',
	'LCStoreCDB' => __DIR__.'/cache/LocalisationCache.php',
	'LCStoreDB' => __DIR__.'/cache/LocalisationCache.php',
	'LCStoreNull' => __DIR__.'/cache/LocalisationCache.php',
	'License' => __DIR__.'/Licenses.php',
	'Licenses' => __DIR__.'/Licenses.php',
	'Linker' => __DIR__.'/Linker.php',
	'LinkFilter' => __DIR__.'/LinkFilter.php',
	'LocalisationCache' => __DIR__.'/cache/LocalisationCache.php',
	'LocalisationCacheBulkLoad' => __DIR__.'/cache/LocalisationCache.php',
	'MagicWord' => __DIR__.'/MagicWord.php',
	'MagicWordArray' => __DIR__.'/MagicWord.php',
	'MailAddress' => __DIR__.'/UserMailer.php',
	'MediaWiki' => __DIR__.'/Wiki.php',
	'MediaWiki_I18N' => __DIR__.'/SkinTemplate.php',
	'MediaWikiVersionFetcher' => __DIR__.'/MediaWikiVersionFetcher.php',
	'Message' => __DIR__.'/Message.php',
	'MessageBlobStore' => __DIR__.'/MessageBlobStore.php',
	'MimeMagic' => __DIR__.'/MimeMagic.php',
	'MWHookException' => __DIR__.'/Hooks.php',
	'MWHttpRequest' => __DIR__.'/HttpFunctions.php',
	'MWInit' => __DIR__.'/Init.php',
	'MWNamespace' => __DIR__.'/Namespace.php',
	'OutputPage' => __DIR__.'/OutputPage.php',
	'Page' => __DIR__.'/WikiPage.php',
	'PageQueryPage' => __DIR__.'/PageQueryPage.php',
	'Pager' => __DIR__.'/Pager.php',
	'PasswordError' => __DIR__.'/User.php',
	'PathRouter' => __DIR__.'/PathRouter.php',
	'PathRouterPatternReplacer' => __DIR__.'/PathRouter.php',
	'PhpHttpRequest' => __DIR__.'/HttpFunctions.php',
	'PoolCounter' => __DIR__.'/poolcounter/PoolCounter.php',
	'PoolCounter_Stub' => __DIR__.'/poolcounter/PoolCounter.php',
	'PoolCounterRedis' => __DIR__.'/poolcounter/PoolCounterRedis.php',
	'PoolCounterWork' => __DIR__.'/poolcounter/PoolCounterWork.php',
	'PoolCounterWorkViaCallback' => __DIR__.'/poolcounter/PoolCounterWork.php',
	'PoolWorkArticleView' => __DIR__.'/WikiPage.php',
	'Preferences' => __DIR__.'/Preferences.php',
	'PreferencesForm' => __DIR__.'/Preferences.php',
	'PrefixSearch' => __DIR__.'/PrefixSearch.php',
	'ProtectionForm' => __DIR__.'/ProtectionForm.php',
	'QueryPage' => __DIR__.'/QueryPage.php',
	'QuickTemplate' => __DIR__.'/SkinTemplate.php',
	'RawMessage' => __DIR__.'/Message.php',
	'ReverseChronologicalPager' => __DIR__.'/Pager.php',
	'RevisionItem' => __DIR__.'/RevisionList.php',
	'RevisionItemBase' => __DIR__.'/RevisionList.php',
	'RevisionListBase' => __DIR__.'/RevisionList.php',
	'Revision' => __DIR__.'/Revision.php',
	'RevisionList' => __DIR__.'/RevisionList.php',
	'RSSFeed' => __DIR__.'/Feed.php',
	'Sanitizer' => __DIR__.'/Sanitizer.php',
	'SiteConfiguration' => __DIR__.'/SiteConfiguration.php',
	'SiteStats' => __DIR__.'/SiteStats.php',
	'SiteStatsInit' => __DIR__.'/SiteStats.php',
	'Skin' => __DIR__.'/Skin.php',
	'SkinTemplate' => __DIR__.'/SkinTemplate.php',
	'SquidPurgeClient' => __DIR__.'/SquidPurgeClient.php',
	'SquidPurgeClientPool' => __DIR__.'/SquidPurgeClient.php',
	'StatCounter' => __DIR__.'/StatCounter.php',
	'Status' => __DIR__.'/Status.php',
	'StreamFile' => __DIR__.'/StreamFile.php',
	'StringPrefixSearch' => __DIR__.'/PrefixSearch.php',
	'StubContLang' => __DIR__.'/StubObject.php',
	'StubObject' => __DIR__.'/StubObject.php',
	'StubUserLang' => __DIR__.'/StubObject.php',
	'TablePager' => __DIR__.'/Pager.php',
	'MWTimestamp' => __DIR__.'/MWTimestamp.php',
	'TimestampException' => __DIR__.'/TimestampException.php',
	'Title' => __DIR__.'/Title.php',
	'TitleArray' => __DIR__.'/TitleArray.php',
	'TitleArrayFromResult' => __DIR__.'/TitleArrayFromResult.php',
	'TitlePrefixSearch' => __DIR__.'/PrefixSearch.php',
	'UploadSourceAdapter' => __DIR__.'/Import.php',
	'UppercaseCollation' => __DIR__.'/Collation.php',
	'User' => __DIR__.'/User.php',
	'UserArray' => __DIR__.'/UserArray.php',
	'UserArrayFromResult' => __DIR__.'/UserArrayFromResult.php',
	'UserCache' => __DIR__.'/cache/UserCache.php',
	'UserMailer' => __DIR__.'/UserMailer.php',
	'UserRightsProxy' => __DIR__.'/UserRightsProxy.php',
	'WantedQueryPage' => __DIR__.'/QueryPage.php',
	'WatchedItem' => __DIR__.'/WatchedItem.php',
	'WebRequest' => __DIR__.'/WebRequest.php',
	'WebRequestUpload' => __DIR__.'/WebRequest.php',
	'WebResponse' => __DIR__.'/WebResponse.php',
	'WikiCategoryPage' => __DIR__.'/WikiCategoryPage.php',
	'WikiExporter' => __DIR__.'/Export.php',
	'WikiFilePage' => __DIR__.'/WikiFilePage.php',
	'WikiImporter' => __DIR__.'/Import.php',
	'WikiPage' => __DIR__.'/WikiPage.php',
	'WikiRevision' => __DIR__.'/Import.php',
	'WikiMap' => __DIR__.'/WikiMap.php',
	'WikiReference' => __DIR__.'/WikiMap.php',
	'Xml' => __DIR__.'/Xml.php',
	'XmlDumpWriter' => __DIR__.'/Export.php',
	'XmlJsCode' => __DIR__.'/Xml.php',
	'XMLReader2' => __DIR__.'/Import.php',
	'XmlSelect' => __DIR__.'/Xml.php',

	# includes/actions
	'Action' => __DIR__.'/actions/Action.php',
	'CachedAction' => __DIR__.'/actions/CachedAction.php',
	'CreditsAction' => __DIR__.'/actions/CreditsAction.php',
	'DeleteAction' => __DIR__.'/actions/DeleteAction.php',
	'EditAction' => __DIR__.'/actions/EditAction.php',
	'FormlessAction' => __DIR__.'/actions/FormlessAction.php',
	'FormAction' => __DIR__.'/actions/FormAction.php',
	'HistoryAction' => __DIR__.'/actions/HistoryAction.php',
	'HistoryPage' => __DIR__.'/actions/HistoryAction.php',
	'HistoryPager' => __DIR__.'/actions/HistoryAction.php',
	'InfoAction' => __DIR__.'/actions/InfoAction.php',
	'MarkpatrolledAction' => __DIR__.'/actions/MarkpatrolledAction.php',
	'ProtectAction' => __DIR__.'/actions/ProtectAction.php',
	'PurgeAction' => __DIR__.'/actions/PurgeAction.php',
	'RawAction' => __DIR__.'/actions/RawAction.php',
	'RawPage' => __DIR__.'/actions/RawAction.php',
	'RenderAction' => __DIR__.'/actions/RenderAction.php',
	'RevertAction' => __DIR__.'/actions/RevertAction.php',
	'RevertFileAction' => __DIR__.'/actions/RevertAction.php',
	'RevisiondeleteAction' => __DIR__.'/actions/RevisiondeleteAction.php',
	'RollbackAction' => __DIR__.'/actions/RollbackAction.php',
	'SubmitAction' => __DIR__.'/actions/EditAction.php',
	'UnprotectAction' => __DIR__.'/actions/ProtectAction.php',
	'UnwatchAction' => __DIR__.'/actions/WatchAction.php',
	'ViewAction' => __DIR__.'/actions/ViewAction.php',
	'WatchAction' => __DIR__.'/actions/WatchAction.php',

	# includes/api
	'ApiBase' => __DIR__.'/api/ApiBase.php',
	'ApiBlock' => __DIR__.'/api/ApiBlock.php',
	'ApiComparePages' => __DIR__.'/api/ApiComparePages.php',
	'ApiCreateAccount' => __DIR__.'/api/ApiCreateAccount.php',
	'ApiDelete' => __DIR__.'/api/ApiDelete.php',
	'ApiDisabled' => __DIR__.'/api/ApiDisabled.php',
	'ApiEditPage' => __DIR__.'/api/ApiEditPage.php',
	'ApiEmailUser' => __DIR__.'/api/ApiEmailUser.php',
	'ApiExpandTemplates' => __DIR__.'/api/ApiExpandTemplates.php',
	'ApiFeedContributions' => __DIR__.'/api/ApiFeedContributions.php',
	'ApiFeedRecentChanges' => __DIR__.'/api/ApiFeedRecentChanges.php',
	'ApiFeedWatchlist' => __DIR__.'/api/ApiFeedWatchlist.php',
	'ApiFileRevert' => __DIR__.'/api/ApiFileRevert.php',
	'ApiFormatBase' => __DIR__.'/api/ApiFormatBase.php',
	'ApiFormatDbg' => __DIR__.'/api/ApiFormatDbg.php',
	'ApiFormatDump' => __DIR__.'/api/ApiFormatDump.php',
	'ApiFormatFeedWrapper' => __DIR__.'/api/ApiFormatBase.php',
	'ApiFormatJson' => __DIR__.'/api/ApiFormatJson.php',
	'ApiFormatNone' => __DIR__.'/api/ApiFormatNone.php',
	'ApiFormatPhp' => __DIR__.'/api/ApiFormatPhp.php',
	'ApiFormatRaw' => __DIR__.'/api/ApiFormatRaw.php',
	'ApiFormatTxt' => __DIR__.'/api/ApiFormatTxt.php',
	'ApiFormatWddx' => __DIR__.'/api/ApiFormatWddx.php',
	'ApiFormatXml' => __DIR__.'/api/ApiFormatXml.php',
	'ApiFormatXmlRsd' => __DIR__.'/api/ApiRsd.php',
	'ApiFormatYaml' => __DIR__.'/api/ApiFormatYaml.php',
	'ApiHelp' => __DIR__.'/api/ApiHelp.php',
	'ApiImageRotate' => __DIR__.'/api/ApiImageRotate.php',
	'ApiImport' => __DIR__.'/api/ApiImport.php',
	'ApiImportReporter' => __DIR__.'/api/ApiImport.php',
	'ApiLogin' => __DIR__.'/api/ApiLogin.php',
	'ApiLogout' => __DIR__.'/api/ApiLogout.php',
	'ApiMain' => __DIR__.'/api/ApiMain.php',
	'ApiModuleManager' => __DIR__.'/api/ApiModuleManager.php',
	'ApiMove' => __DIR__.'/api/ApiMove.php',
	'ApiOpenSearch' => __DIR__.'/api/ApiOpenSearch.php',
	'ApiOptions' => __DIR__.'/api/ApiOptions.php',
	'ApiPageSet' => __DIR__.'/api/ApiPageSet.php',
	'ApiParamInfo' => __DIR__.'/api/ApiParamInfo.php',
	'ApiParse' => __DIR__.'/api/ApiParse.php',
	'ApiPatrol' => __DIR__.'/api/ApiPatrol.php',
	'ApiProtect' => __DIR__.'/api/ApiProtect.php',
	'ApiPurge' => __DIR__.'/api/ApiPurge.php',
	'ApiQuery' => __DIR__.'/api/ApiQuery.php',
	'ApiQueryAllCategories' => __DIR__.'/api/ApiQueryAllCategories.php',
	'ApiQueryAllImages' => __DIR__.'/api/ApiQueryAllImages.php',
	'ApiQueryAllLinks' => __DIR__.'/api/ApiQueryAllLinks.php',
	'ApiQueryAllMessages' => __DIR__.'/api/ApiQueryAllMessages.php',
	'ApiQueryAllPages' => __DIR__.'/api/ApiQueryAllPages.php',
	'ApiQueryAllUsers' => __DIR__.'/api/ApiQueryAllUsers.php',
	'ApiQueryBacklinks' => __DIR__.'/api/ApiQueryBacklinks.php',
	'ApiQueryBase' => __DIR__.'/api/ApiQueryBase.php',
	'ApiQueryBlocks' => __DIR__.'/api/ApiQueryBlocks.php',
	'ApiQueryCategories' => __DIR__.'/api/ApiQueryCategories.php',
	'ApiQueryCategoryInfo' => __DIR__.'/api/ApiQueryCategoryInfo.php',
	'ApiQueryCategoryMembers' => __DIR__.'/api/ApiQueryCategoryMembers.php',
	'ApiQueryContributions' => __DIR__.'/api/ApiQueryUserContributions.php',
	'ApiQueryContributors' => __DIR__.'/api/ApiQueryContributors.php',
	'ApiQueryDeletedrevs' => __DIR__.'/api/ApiQueryDeletedrevs.php',
	'ApiQueryDisabled' => __DIR__.'/api/ApiQueryDisabled.php',
	'ApiQueryDuplicateFiles' => __DIR__.'/api/ApiQueryDuplicateFiles.php',
	'ApiQueryExternalLinks' => __DIR__.'/api/ApiQueryExternalLinks.php',
	'ApiQueryExtLinksUsage' => __DIR__.'/api/ApiQueryExtLinksUsage.php',
	'ApiQueryFilearchive' => __DIR__.'/api/ApiQueryFilearchive.php',
	'ApiQueryGeneratorBase' => __DIR__.'/api/ApiQueryBase.php',
	'ApiQueryImageInfo' => __DIR__.'/api/ApiQueryImageInfo.php',
	'ApiQueryImages' => __DIR__.'/api/ApiQueryImages.php',
	'ApiQueryInfo' => __DIR__.'/api/ApiQueryInfo.php',
	'ApiQueryIWBacklinks' => __DIR__.'/api/ApiQueryIWBacklinks.php',
	'ApiQueryIWLinks' => __DIR__.'/api/ApiQueryIWLinks.php',
	'ApiQueryLangBacklinks' => __DIR__.'/api/ApiQueryLangBacklinks.php',
	'ApiQueryLangLinks' => __DIR__.'/api/ApiQueryLangLinks.php',
	'ApiQueryLinks' => __DIR__.'/api/ApiQueryLinks.php',
	'ApiQueryLogEvents' => __DIR__.'/api/ApiQueryLogEvents.php',
	'ApiQueryORM' => __DIR__.'/api/ApiQueryORM.php',
	'ApiQueryPageProps' => __DIR__.'/api/ApiQueryPageProps.php',
	'ApiQueryPagesWithProp' => __DIR__.'/api/ApiQueryPagesWithProp.php',
	'ApiQueryPagePropNames' => __DIR__.'/api/ApiQueryPagePropNames.php',
	'ApiQueryPrefixSearch' => __DIR__.'/api/ApiQueryPrefixSearch.php',
	'ApiQueryProtectedTitles' => __DIR__.'/api/ApiQueryProtectedTitles.php',
	'ApiQueryQueryPage' => __DIR__.'/api/ApiQueryQueryPage.php',
	'ApiQueryRandom' => __DIR__.'/api/ApiQueryRandom.php',
	'ApiQueryRecentChanges' => __DIR__.'/api/ApiQueryRecentChanges.php',
	'ApiQueryFileRepoInfo' => __DIR__.'/api/ApiQueryFileRepoInfo.php',
	'ApiQueryRedirects' => __DIR__.'/api/ApiQueryRedirects.php',
	'ApiQueryRevisions' => __DIR__.'/api/ApiQueryRevisions.php',
	'ApiQuerySearch' => __DIR__.'/api/ApiQuerySearch.php',
	'ApiQuerySiteinfo' => __DIR__.'/api/ApiQuerySiteinfo.php',
	'ApiQueryStashImageInfo' => __DIR__.'/api/ApiQueryStashImageInfo.php',
	'ApiQueryTags' => __DIR__.'/api/ApiQueryTags.php',
	'ApiQueryUserInfo' => __DIR__.'/api/ApiQueryUserInfo.php',
	'ApiQueryUsers' => __DIR__.'/api/ApiQueryUsers.php',
	'ApiQueryWatchlist' => __DIR__.'/api/ApiQueryWatchlist.php',
	'ApiQueryWatchlistRaw' => __DIR__.'/api/ApiQueryWatchlistRaw.php',
	'ApiResult' => __DIR__.'/api/ApiResult.php',
	'ApiRevisionDelete' => __DIR__.'/api/ApiRevisionDelete.php',
	'ApiRollback' => __DIR__.'/api/ApiRollback.php',
	'ApiRsd' => __DIR__.'/api/ApiRsd.php',
	'ApiSetNotificationTimestamp' => __DIR__.'/api/ApiSetNotificationTimestamp.php',
	'ApiTokens' => __DIR__.'/api/ApiTokens.php',
	'ApiUnblock' => __DIR__.'/api/ApiUnblock.php',
	'ApiUndelete' => __DIR__.'/api/ApiUndelete.php',
	'ApiUpload' => __DIR__.'/api/ApiUpload.php',
	'ApiUserrights' => __DIR__.'/api/ApiUserrights.php',
	'ApiWatch' => __DIR__.'/api/ApiWatch.php',
	'UsageException' => __DIR__.'/api/ApiMain.php',

	# includes/cache
	'BacklinkCache' => __DIR__.'/cache/BacklinkCache.php',
	'CacheDependency' => __DIR__.'/cache/CacheDependency.php',
	'ConstantDependency' => __DIR__.'/cache/CacheDependency.php',
	'DependencyWrapper' => __DIR__.'/cache/CacheDependency.php',
	'FileCacheBase' => __DIR__.'/cache/FileCacheBase.php',
	'FileDependency' => __DIR__.'/cache/CacheDependency.php',
	'GenderCache' => __DIR__.'/cache/GenderCache.php',
	'GlobalDependency' => __DIR__.'/cache/CacheDependency.php',
	'HTMLFileCache' => __DIR__.'/cache/HTMLFileCache.php',
	'LinkBatch' => __DIR__.'/cache/LinkBatch.php',
	'LinkCache' => __DIR__.'/cache/LinkCache.php',
	'MapCacheLRU' => __DIR__.'/cache/MapCacheLRU.php',
	'MessageCache' => __DIR__."/cache/MessageCache.php",
	'ObjectFileCache' => __DIR__."/cache/ObjectFileCache.php",
	'ResourceFileCache' => __DIR__."/cache/ResourceFileCache.php",

	# includes/changes
	'ChangesList' => __DIR__.'/changes/ChangesList.php',
	'EnhancedChangesList' => __DIR__.'/changes/EnhancedChangesList.php',
	'OldChangesList' => __DIR__.'/changes/OldChangesList.php',
	'RCCacheEntry' => __DIR__.'/changes/RCCacheEntry.php',
	'RCCacheEntryFactory' => __DIR__.'/changes/RCCacheEntryFactory.php',
	'RecentChange' => __DIR__.'/changes/RecentChange.php',

	# includes/clientpool
	'RedisConnectionPool' => __DIR__.'/clientpool/RedisConnectionPool.php',
	'RedisConnRef' => __DIR__.'/clientpool/RedisConnectionPool.php',

	# includes/composer
	'ComposerPackageModifier' => __DIR__.'/composer/ComposerPackageModifier.php',
	'ComposerVersionNormalizer' => __DIR__.'/composer/ComposerVersionNormalizer.php',

	# includes/config
	'Config' => __DIR__.'/config/Config.php',
	'ConfigException' => __DIR__.'/config/ConfigException.php',
	'ConfigFactory' => __DIR__.'/config/ConfigFactory.php',
	'GlobalVarConfig' => __DIR__.'/config/GlobalVarConfig.php',

	# includes/content
	'AbstractContent' => __DIR__.'/content/AbstractContent.php',
	'ContentHandler' => __DIR__.'/content/ContentHandler.php',
	'Content' => __DIR__.'/content/Content.php',
	'CssContentHandler' => __DIR__.'/content/CssContentHandler.php',
	'CssContent' => __DIR__.'/content/CssContent.php',
	'JavaScriptContentHandler' => __DIR__.'/content/JavaScriptContentHandler.php',
	'JavaScriptContent' => __DIR__.'/content/JavaScriptContent.php',
	'MessageContent' => __DIR__.'/content/MessageContent.php',
	'MWContentSerializationException' => __DIR__.'/content/ContentHandler.php',
	'TextContentHandler' => __DIR__.'/content/TextContentHandler.php',
	'TextContent' => __DIR__.'/content/TextContent.php',
	'WikitextContentHandler' => __DIR__.'/content/WikitextContentHandler.php',
	'WikitextContent' => __DIR__.'/content/WikitextContent.php',

	# includes/context
	'ContextSource' => __DIR__.'/context/ContextSource.php',
	'DerivativeContext' => __DIR__.'/context/DerivativeContext.php',
	'IContextSource' => __DIR__.'/context/IContextSource.php',
	'RequestContext' => __DIR__.'/context/RequestContext.php',

	# includes/dao
	'IDBAccessObject' => __DIR__.'/dao/IDBAccessObject.php',
	'DBAccessBase' => __DIR__.'/dao/DBAccessBase.php',

	# includes/db
	'Blob' => __DIR__.'/db/DatabaseUtility.php',
	'ChronologyProtector' => __DIR__.'/db/ChronologyProtector.php',
	'CloneDatabase' => __DIR__.'/db/CloneDatabase.php',
	'DatabaseBase' => __DIR__.'/db/Database.php',
	'DatabaseMssql' => __DIR__.'/db/DatabaseMssql.php',
	'DatabaseMysql' => __DIR__.'/db/DatabaseMysql.php',
	'DatabaseMysqlBase' => __DIR__.'/db/DatabaseMysqlBase.php',
	'DatabaseMysqli' => __DIR__.'/db/DatabaseMysqli.php',
	'DatabaseOracle' => __DIR__.'/db/DatabaseOracle.php',
	'DatabasePostgres' => __DIR__.'/db/DatabasePostgres.php',
	'DatabaseSqlite' => __DIR__.'/db/DatabaseSqlite.php',
	'DatabaseSqliteStandalone' => __DIR__.'/db/DatabaseSqlite.php',
	'DatabaseType' => __DIR__.'/db/Database.php',
	'DBAccessError' => __DIR__.'/db/LBFactory.php',
	'DBConnectionError' => __DIR__.'/db/DatabaseError.php',
	'DBConnRef' => __DIR__.'/db/LoadBalancer.php',
	'DBError' => __DIR__.'/db/DatabaseError.php',
	'DBExpectedError' => __DIR__.'/db/DatabaseError.php',
	'DBObject' => __DIR__.'/db/DatabaseUtility.php',
	'IDatabase'  => __DIR__.'/db/Database.php',
	'IORMRow' => __DIR__.'/db/IORMRow.php',
	'IORMTable' => __DIR__.'/db/IORMTable.php',
	'DBMasterPos' => __DIR__.'/db/DatabaseUtility.php',
	'DBQueryError' => __DIR__.'/db/DatabaseError.php',
	'DBUnexpectedError' => __DIR__.'/db/DatabaseError.php',
	'FakeResultWrapper' => __DIR__.'/db/DatabaseUtility.php',
	'Field' => __DIR__.'/db/DatabaseUtility.php',
	'LBFactory' => __DIR__.'/db/LBFactory.php',
	'LBFactoryFake' => __DIR__.'/db/LBFactory.php',
	'LBFactoryMulti' => __DIR__.'/db/LBFactoryMulti.php',
	'LBFactorySimple' => __DIR__.'/db/LBFactory.php',
	'LBFactorySingle' => __DIR__.'/db/LBFactorySingle.php',
	'LikeMatch' => __DIR__.'/db/DatabaseUtility.php',
	'LoadBalancer' => __DIR__.'/db/LoadBalancer.php',
	'LoadBalancerSingle' => __DIR__.'/db/LBFactorySingle.php',
	'LoadMonitor' => __DIR__.'/db/LoadMonitor.php',
	'LoadMonitorMySQL' => __DIR__.'/db/LoadMonitor.php',
	'LoadMonitorNull' => __DIR__.'/db/LoadMonitor.php',
	'MssqlField' => __DIR__.'/db/DatabaseMssql.php',
	'MssqlBlob' => __DIR__.'/db/DatabaseMssql.php',
	'MssqlResultWrapper' => __DIR__.'/db/DatabaseMssql.php',
	'MySQLField' => __DIR__.'/db/DatabaseMysqlBase.php',
	'MySQLMasterPos' => __DIR__.'/db/DatabaseMysqlBase.php',
	'ORAField' => __DIR__.'/db/DatabaseOracle.php',
	'ORAResult' => __DIR__.'/db/DatabaseOracle.php',
	'ORMIterator' => __DIR__.'/db/ORMIterator.php',
	'ORMResult' => __DIR__.'/db/ORMResult.php',
	'ORMRow' => __DIR__.'/db/ORMRow.php',
	'ORMTable' => __DIR__.'/db/ORMTable.php',
	'PostgresField' => __DIR__.'/db/DatabasePostgres.php',
	'PostgresTransactionState' => __DIR__.'/db/DatabasePostgres.php',
	'ResultWrapper' => __DIR__.'/db/DatabaseUtility.php',
	'SavepointPostgres' => __DIR__.'/db/DatabasePostgres.php',
	'SQLiteField' => __DIR__.'/db/DatabaseSqlite.php',

	# includes/debug
	'MWDebug' => __DIR__.'/debug/Debug.php',

	# includes/deferred
	'DataUpdate' => __DIR__.'/deferred/DataUpdate.php',
	'DeferrableUpdate' => __DIR__.'/deferred/DeferredUpdates.php',
	'DeferredUpdates' => __DIR__.'/deferred/DeferredUpdates.php',
	'HTMLCacheUpdate' => __DIR__.'/deferred/HTMLCacheUpdate.php',
	'LinksDeletionUpdate' => __DIR__.'/deferred/LinksUpdate.php',
	'LinksUpdate' => __DIR__.'/deferred/LinksUpdate.php',
	'MWCallableUpdate' => __DIR__.'/deferred/CallableUpdate.php',
	'SearchUpdate' => __DIR__.'/deferred/SearchUpdate.php',
	'SiteStatsUpdate' => __DIR__.'/deferred/SiteStatsUpdate.php',
	'SqlDataUpdate' => __DIR__.'/deferred/SqlDataUpdate.php',
	'SquidUpdate' => __DIR__.'/deferred/SquidUpdate.php',
	'ViewCountUpdate' => __DIR__.'/deferred/ViewCountUpdate.php',

	# includes/diff
	'DiffEngine' => __DIR__.'/diff/DairikiDiff.php',
	'DiffOp' => __DIR__.'/diff/DairikiDiff.php',
	'DiffOpAdd' => __DIR__.'/diff/DairikiDiff.php',
	'DiffOpChange' => __DIR__.'/diff/DairikiDiff.php',
	'DiffOpCopy' => __DIR__.'/diff/DairikiDiff.php',
	'DiffOpDelete' => __DIR__.'/diff/DairikiDiff.php',
	'HWLDFWordAccumulator' => __DIR__.'/diff/DairikiDiff.php',
	'ArrayDiffFormatter' => __DIR__.'/diff/ArrayDiffFormatter.php',
	'Diff' => __DIR__.'/diff/DairikiDiff.php',
	'DifferenceEngine' => __DIR__.'/diff/DifferenceEngine.php',
	'DiffFormatter' => __DIR__.'/diff/DiffFormatter.php',
	'MappedDiff' => __DIR__.'/diff/DairikiDiff.php',
	'RangeDifference' => __DIR__.'/diff/WikiDiff3.php',
	'TableDiffFormatter' => __DIR__.'/diff/TableDiffFormatter.php',
	'UnifiedDiffFormatter' => __DIR__.'/diff/UnifiedDiffFormatter.php',
	'WikiDiff3' => __DIR__.'/diff/WikiDiff3.php',
	'WordLevelDiff' => __DIR__.'/diff/DairikiDiff.php',

	# includes/exception
	'UserBlockedError' => __DIR__.'/exception/UserBlockedError.php',
	'UserNotLoggedIn' => __DIR__.'/exception/UserNotLoggedIn.php',
	'ThrottledError' => __DIR__.'/exception/ThrottledError.php',
	'ReadOnlyError' => __DIR__.'/exception/ReadOnlyError.php',
	'PermissionsError' => __DIR__.'/exception/PermissionsError.php',
	'MWException' => __DIR__.'/exception/MWException.php',
	'MWExceptionHandler' => __DIR__.'/exception/MWExceptionHandler.php',
	'HttpError' => __DIR__.'/exception/HttpError.php',
	'BadTitleError' => __DIR__.'/exception/BadTitleError.php',
	'ErrorPageError' => __DIR__.'/exception/ErrorPageError.php',
	'FatalError' => __DIR__.'/exception/FatalError.php',

	# includes/externalstore
	'ExternalStore' => __DIR__.'/externalstore/ExternalStore.php',
	'ExternalStoreDB' => __DIR__.'/externalstore/ExternalStoreDB.php',
	'ExternalStoreHttp' => __DIR__.'/externalstore/ExternalStoreHttp.php',
	'ExternalStoreMedium' => __DIR__.'/externalstore/ExternalStoreMedium.php',
	'ExternalStoreMwstore' => __DIR__.'/externalstore/ExternalStoreMwstore.php',

	# includes/filebackend
	'FileBackendGroup' => __DIR__.'/filebackend/FileBackendGroup.php',
	'FileBackend' => __DIR__.'/filebackend/FileBackend.php',
	'FileBackendError' => __DIR__.'/filebackend/FileBackend.php',
	'FileBackendException' => __DIR__.'/filebackend/FileBackend.php',
	'FileBackendStore' => __DIR__.'/filebackend/FileBackendStore.php',
	'FileBackendStoreShardListIterator' => __DIR__.'/filebackend/FileBackendStore.php',
	'FileBackendStoreShardDirIterator' => __DIR__.'/filebackend/FileBackendStore.php',
	'FileBackendStoreShardFileIterator' => __DIR__.'/filebackend/FileBackendStore.php',
	'FileBackendMultiWrite' => __DIR__.'/filebackend/FileBackendMultiWrite.php',
	'FileBackendStoreOpHandle' => __DIR__.'/filebackend/FileBackendStore.php',
	'FSFile' => __DIR__.'/filebackend/FSFile.php',
	'FSFileBackend' => __DIR__.'/filebackend/FSFileBackend.php',
	'FSFileBackendList' => __DIR__.'/filebackend/FSFileBackend.php',
	'FSFileBackendDirList' => __DIR__.'/filebackend/FSFileBackend.php',
	'FSFileBackendFileList' => __DIR__.'/filebackend/FSFileBackend.php',
	'FSFileOpHandle' => __DIR__.'/filebackend/FSFileBackend.php',
	'MemoryFileBackend' => __DIR__.'/filebackend/MemoryFileBackend.php',
	'SwiftFileBackend' => __DIR__.'/filebackend/SwiftFileBackend.php',
	'SwiftFileBackendList' => __DIR__.'/filebackend/SwiftFileBackend.php',
	'SwiftFileBackendDirList' => __DIR__.'/filebackend/SwiftFileBackend.php',
	'SwiftFileBackendFileList' => __DIR__.'/filebackend/SwiftFileBackend.php',
	'SwiftFileOpHandle' => __DIR__.'/filebackend/SwiftFileBackend.php',
	'TempFSFile' => __DIR__.'/filebackend/TempFSFile.php',
	'FileJournal' => __DIR__.'/filebackend/filejournal/FileJournal.php',
	'DBFileJournal' => __DIR__.'/filebackend/filejournal/DBFileJournal.php',
	'NullFileJournal' => __DIR__.'/filebackend/filejournal/FileJournal.php',
	'LockManagerGroup' => __DIR__.'/filebackend/lockmanager/LockManagerGroup.php',
	'LockManager' => __DIR__.'/filebackend/lockmanager/LockManager.php',
	'ScopedLock' => __DIR__.'/filebackend/lockmanager/ScopedLock.php',
	'FSLockManager' => __DIR__.'/filebackend/lockmanager/FSLockManager.php',
	'DBLockManager' => __DIR__.'/filebackend/lockmanager/DBLockManager.php',
	'MemcLockManager' => __DIR__.'/filebackend/lockmanager/MemcLockManager.php',
	'QuorumLockManager' => __DIR__.'/filebackend/lockmanager/QuorumLockManager.php',
	'MySqlLockManager' => __DIR__.'/filebackend/lockmanager/DBLockManager.php',
	'PostgreSqlLockManager' => __DIR__.'/filebackend/lockmanager/DBLockManager.php',
	'RedisLockManager' => __DIR__.'/filebackend/lockmanager/RedisLockManager.php',
	'NullLockManager' => __DIR__.'/filebackend/lockmanager/LockManager.php',
	'FileOp' => __DIR__.'/filebackend/FileOp.php',
	'FileOpBatch' => __DIR__.'/filebackend/FileOpBatch.php',
	'StoreFileOp' => __DIR__.'/filebackend/FileOp.php',
	'CopyFileOp' => __DIR__.'/filebackend/FileOp.php',
	'MoveFileOp' => __DIR__.'/filebackend/FileOp.php',
	'DeleteFileOp' => __DIR__.'/filebackend/FileOp.php',
	'CreateFileOp' => __DIR__.'/filebackend/FileOp.php',
	'DescribeFileOp' => __DIR__.'/filebackend/FileOp.php',
	'NullFileOp' => __DIR__.'/filebackend/FileOp.php',

	# includes/filerepo
	'FileRepo' => __DIR__.'/filerepo/FileRepo.php',
	'FileRepoStatus' => __DIR__.'/filerepo/FileRepoStatus.php',
	'ForeignAPIRepo' => __DIR__.'/filerepo/ForeignAPIRepo.php',
	'ForeignDBRepo' => __DIR__.'/filerepo/ForeignDBRepo.php',
	'ForeignDBViaLBRepo' => __DIR__.'/filerepo/ForeignDBViaLBRepo.php',
	'FSRepo' => __DIR__.'/filerepo/FSRepo.php',
	'LocalRepo' => __DIR__.'/filerepo/LocalRepo.php',
	'NullRepo' => __DIR__.'/filerepo/NullRepo.php',
	'RepoGroup' => __DIR__.'/filerepo/RepoGroup.php',
	'TempFileRepo' => __DIR__.'/filerepo/FileRepo.php',

	# includes/filerepo/file
	'ArchivedFile' => __DIR__.'/filerepo/file/ArchivedFile.php',
	'File' => __DIR__.'/filerepo/file/File.php',
	'ForeignAPIFile' => __DIR__.'/filerepo/file/ForeignAPIFile.php',
	'ForeignDBFile' => __DIR__.'/filerepo/file/ForeignDBFile.php',
	'LocalFile' => __DIR__.'/filerepo/file/LocalFile.php',
	'LocalFileDeleteBatch' => __DIR__.'/filerepo/file/LocalFile.php',
	'LocalFileMoveBatch' => __DIR__.'/filerepo/file/LocalFile.php',
	'LocalFileRestoreBatch' => __DIR__.'/filerepo/file/LocalFile.php',
	'OldLocalFile' => __DIR__.'/filerepo/file/OldLocalFile.php',
	'UnregisteredLocalFile' => __DIR__.'/filerepo/file/UnregisteredLocalFile.php',

	# includes/installer
	'CliInstaller' => __DIR__.'/installer/CliInstaller.php',
	'DatabaseInstaller' => __DIR__.'/installer/DatabaseInstaller.php',
	'DatabaseUpdater' => __DIR__.'/installer/DatabaseUpdater.php',
	'InstallDocFormatter' => __DIR__.'/installer/InstallDocFormatter.php',
	'Installer' => __DIR__.'/installer/Installer.php',
	'LocalSettingsGenerator' => __DIR__.'/installer/LocalSettingsGenerator.php',
	'MssqlInstaller' => __DIR__.'/installer/MssqlInstaller.php',
	'MssqlUpdater' => __DIR__.'/installer/MssqlUpdater.php',
	'MysqlInstaller' => __DIR__.'/installer/MysqlInstaller.php',
	'MysqlUpdater' => __DIR__.'/installer/MysqlUpdater.php',
	'OracleInstaller' => __DIR__.'/installer/OracleInstaller.php',
	'OracleUpdater' => __DIR__.'/installer/OracleUpdater.php',
	'PhpXmlBugTester' => __DIR__.'/installer/PhpBugTests.php',
	'PostgresInstaller' => __DIR__.'/installer/PostgresInstaller.php',
	'PostgresUpdater' => __DIR__.'/installer/PostgresUpdater.php',
	'SqliteInstaller' => __DIR__.'/installer/SqliteInstaller.php',
	'SqliteUpdater' => __DIR__.'/installer/SqliteUpdater.php',
	'WebInstaller' => __DIR__.'/installer/WebInstaller.php',
	'WebInstaller_Complete' => __DIR__.'/installer/WebInstallerPage.php',
	'WebInstaller_Copying' => __DIR__.'/installer/WebInstallerPage.php',
	'WebInstaller_DBConnect' => __DIR__.'/installer/WebInstallerPage.php',
	'WebInstaller_DBSettings' => __DIR__.'/installer/WebInstallerPage.php',
	'WebInstaller_Document' => __DIR__.'/installer/WebInstallerPage.php',
	'WebInstaller_ExistingWiki' => __DIR__.'/installer/WebInstallerPage.php',
	'WebInstaller_Install' => __DIR__.'/installer/WebInstallerPage.php',
	'WebInstaller_Language' => __DIR__.'/installer/WebInstallerPage.php',
	'WebInstaller_Name' => __DIR__.'/installer/WebInstallerPage.php',
	'WebInstaller_Options' => __DIR__.'/installer/WebInstallerPage.php',
	'WebInstaller_Readme' => __DIR__.'/installer/WebInstallerPage.php',
	'WebInstaller_ReleaseNotes' => __DIR__.'/installer/WebInstallerPage.php',
	'WebInstaller_Restart' => __DIR__.'/installer/WebInstallerPage.php',
	'WebInstaller_Upgrade' => __DIR__.'/installer/WebInstallerPage.php',
	'WebInstaller_UpgradeDoc' => __DIR__.'/installer/WebInstallerPage.php',
	'WebInstaller_Welcome' => __DIR__.'/installer/WebInstallerPage.php',
	'WebInstallerOutput' => __DIR__.'/installer/WebInstallerOutput.php',
	'WebInstallerPage' => __DIR__.'/installer/WebInstallerPage.php',

	# includes/job
	'IJobSpecification' => __DIR__.'/jobqueue/JobSpecification.php',
	'Job' => __DIR__.'/jobqueue/Job.php',
	'JobQueue' => __DIR__.'/jobqueue/JobQueue.php',
	'JobQueueAggregator' => __DIR__.'/jobqueue/aggregator/JobQueueAggregator.php',
	'JobQueueAggregatorMemc' => __DIR__.'/jobqueue/aggregator/JobQueueAggregatorMemc.php',
	'JobQueueAggregatorRedis' => __DIR__.'/jobqueue/aggregator/JobQueueAggregatorRedis.php',
	'JobQueueDB' => __DIR__.'/jobqueue/JobQueueDB.php',
	'JobQueueConnectionError' => __DIR__.'/jobqueue/JobQueue.php',
	'JobQueueError' => __DIR__.'/jobqueue/JobQueue.php',
	'JobQueueGroup' => __DIR__.'/jobqueue/JobQueueGroup.php',
	'JobQueueFederated' => __DIR__.'/jobqueue/JobQueueFederated.php',
	'JobQueueRedis' => __DIR__.'/jobqueue/JobQueueRedis.php',
	'JobSpecification' => __DIR__.'/jobqueue/JobSpecification.php',

	# includes/jobqueue/jobs
	'DoubleRedirectJob' => __DIR__.'/jobqueue/jobs/DoubleRedirectJob.php',
	'DuplicateJob' => __DIR__.'/jobqueue/jobs/DuplicateJob.php',
	'EmaillingJob' => __DIR__.'/jobqueue/jobs/EmaillingJob.php',
	'EnotifNotifyJob' => __DIR__.'/jobqueue/jobs/EnotifNotifyJob.php',
	'HTMLCacheUpdateJob' => __DIR__.'/jobqueue/jobs/HTMLCacheUpdateJob.php',
	'NullJob' => __DIR__.'/jobqueue/jobs/NullJob.php',
	'RefreshLinksJob' => __DIR__.'/jobqueue/jobs/RefreshLinksJob.php',
	'RefreshLinksJob2' => __DIR__.'/jobqueue/jobs/RefreshLinksJob2.php',
	'UploadFromUrlJob' => __DIR__.'/jobqueue/jobs/UploadFromUrlJob.php',
	'AssembleUploadChunksJob' => __DIR__.'/jobqueue/jobs/AssembleUploadChunksJob.php',
	'PublishStashedFileJob' => __DIR__.'/jobqueue/jobs/PublishStashedFileJob.php',

	# includes/jobqueue/utils
	'BacklinkJobUtils' => __DIR__.'/jobqueue/utils/BacklinkJobUtils.php',

	# includes/json
	'FormatJson' => __DIR__.'/json/FormatJson.php',

	# includes/libs
	'CSSJanus' => __DIR__.'/libs/CSSJanus.php',
	'CSSJanus_Tokenizer' => __DIR__.'/libs/CSSJanus.php',
	'CSSMin' => __DIR__.'/libs/CSSMin.php',
	'GenericArrayObject' => __DIR__.'/libs/GenericArrayObject.php',
	'HashRing' => __DIR__.'/libs/HashRing.php',
	'HttpStatus' => __DIR__.'/libs/HttpStatus.php',
	'IEContentAnalyzer' => __DIR__.'/libs/IEContentAnalyzer.php',
	'IEUrlExtension' => __DIR__.'/libs/IEUrlExtension.php',
	'MappedIterator' => __DIR__.'/libs/MappedIterator.php',
	'JavaScriptMinifier' => __DIR__.'/libs/JavaScriptMinifier.php',
	'JSCompilerContext' => __DIR__.'/libs/jsminplus.php',
	'JSMinPlus' => __DIR__.'/libs/jsminplus.php',
	'JSNode' => __DIR__.'/libs/jsminplus.php',
	'JSParser' => __DIR__.'/libs/jsminplus.php',
	'JSToken' => __DIR__.'/libs/jsminplus.php',
	'JSTokenizer' => __DIR__.'/libs/jsminplus.php',
	'MultiHttpClient' => __DIR__.'/libs/MultiHttpClient.php',
	'MWMessagePack' => __DIR__.'/libs/MWMessagePack.php',
	'ProcessCacheLRU' => __DIR__.'/libs/ProcessCacheLRU.php',
	'RunningStat' => __DIR__.'/libs/RunningStat.php',
	'ScopedCallback' => __DIR__.'/libs/ScopedCallback.php',
	'ScopedPHPTimeout' => __DIR__.'/libs/ScopedPHPTimeout.php',
	'XmlTypeCheck' => __DIR__.'/libs/XmlTypeCheck.php',

	# includes/libs/lessphp
	'lessc' => __DIR__.'/libs/lessc.inc.php',
	'lessc_parser' => __DIR__.'/libs/lessc.inc.php',
	'lessc_formatter_classic' => __DIR__.'/libs/lessc.inc.php',
	'lessc_formatter_compressed' => __DIR__.'/libs/lessc.inc.php',
	'lessc_formatter_lessjs' => __DIR__.'/libs/lessc.inc.php',

	# includes/logging
	'DatabaseLogEntry' => __DIR__.'/logging/LogEntry.php',
	'DeleteLogFormatter' => __DIR__.'/logging/DeleteLogFormatter.php',
	'LegacyLogFormatter' => __DIR__.'/logging/LogFormatter.php',
	'LogEntry' => __DIR__.'/logging/LogEntry.php',
	'LogEventsList' => __DIR__.'/logging/LogEventsList.php',
	'LogEntryBase' => __DIR__.'/logging/LogEntry.php',
	'LogFormatter' => __DIR__.'/logging/LogFormatter.php',
	'LogPage' => __DIR__.'/logging/LogPage.php',
	'LogPager' => __DIR__.'/logging/LogPager.php',
	'ManualLogEntry' => __DIR__.'/logging/LogEntry.php',
	'MoveLogFormatter' => __DIR__.'/logging/MoveLogFormatter.php',
	'NewUsersLogFormatter' => __DIR__.'/logging/NewUsersLogFormatter.php',
	'PatrolLog' => __DIR__.'/logging/PatrolLog.php',
	'PatrolLogFormatter' => __DIR__.'/logging/PatrolLogFormatter.php',
	'RCDatabaseLogEntry' => __DIR__.'/logging/LogEntry.php',
	'RightsLogFormatter' => __DIR__.'/logging/RightsLogFormatter.php',

	# Image gallery

	'ImageGallery' => __DIR__.'/gallery/TraditionalImageGallery.php',
	'ImageGalleryBase' => __DIR__.'/gallery/ImageGalleryBase.php',
	'NolinesImageGallery' => __DIR__.'/gallery/NolinesImageGallery.php',
	'TraditionalImageGallery' => __DIR__.'/gallery/TraditionalImageGallery.php',
	'PackedImageGallery' => __DIR__.'/gallery/PackedImageGallery.php',
	'PackedHoverImageGallery' => __DIR__.'/gallery/PackedOverlayImageGallery.php',
	'PackedOverlayImageGallery' => __DIR__.'/gallery/PackedOverlayImageGallery.php',

	# includes/media
	'BitmapHandler' => __DIR__.'/media/Bitmap.php',
	'BitmapHandler_ClientOnly' => __DIR__.'/media/Bitmap_ClientOnly.php',
	'BitmapMetadataHandler' => __DIR__.'/media/BitmapMetadataHandler.php',
	'BmpHandler' => __DIR__.'/media/BMP.php',
	'DjVuHandler' => __DIR__.'/media/DjVu.php',
	'DjVuImage' => __DIR__.'/media/DjVuImage.php',
	'Exif' => __DIR__.'/media/Exif.php',
	'ExifBitmapHandler' => __DIR__.'/media/ExifBitmap.php',
	'FormatExif' => __DIR__.'/media/FormatMetadata.php',
	'FormatMetadata' => __DIR__.'/media/FormatMetadata.php',
	'GIFHandler' => __DIR__.'/media/GIF.php',
	'GIFMetadataExtractor' => __DIR__.'/media/GIFMetadataExtractor.php',
	'ImageHandler' => __DIR__.'/media/ImageHandler.php',
	'IPTC' => __DIR__.'/media/IPTC.php',
	'JpegHandler' => __DIR__.'/media/Jpeg.php',
	'JpegMetadataExtractor' => __DIR__.'/media/JpegMetadataExtractor.php',
	'MediaHandler' => __DIR__.'/media/MediaHandler.php',
	'MediaTransformError' => __DIR__.'/media/MediaTransformOutput.php',
	'MediaTransformOutput' => __DIR__.'/media/MediaTransformOutput.php',
	'PNGHandler' => __DIR__.'/media/PNG.php',
	'PNGMetadataExtractor' => __DIR__.'/media/PNGMetadataExtractor.php',
	'SvgHandler' => __DIR__.'/media/SVG.php',
	'SVGMetadataExtractor' => __DIR__.'/media/SVGMetadataExtractor.php',
	'SVGReader' => __DIR__.'/media/SVGMetadataExtractor.php',
	'ThumbnailImage' => __DIR__.'/media/MediaTransformOutput.php',
	'TiffHandler' => __DIR__.'/media/Tiff.php',
	'TransformParameterError' => __DIR__.'/media/MediaTransformOutput.php',
	'XCFHandler' => __DIR__.'/media/XCF.php',
	'XMPInfo' => __DIR__.'/media/XMPInfo.php',
	'XMPReader' => __DIR__.'/media/XMP.php',
	'XMPValidate' => __DIR__.'/media/XMPValidate.php',

	# includes/normal
	'UtfNormal' => __DIR__.'/normal/UtfNormal.php',

	# includes/objectcache
	'APCBagOStuff' => __DIR__.'/objectcache/APCBagOStuff.php',
	'BagOStuff' => __DIR__.'/objectcache/BagOStuff.php',
	'EmptyBagOStuff' => __DIR__.'/objectcache/EmptyBagOStuff.php',
	'HashBagOStuff' => __DIR__.'/objectcache/HashBagOStuff.php',
	'MediaWikiBagOStuff' => __DIR__.'/objectcache/SqlBagOStuff.php',
	'MemCachedClientforWiki' => __DIR__.'/objectcache/MemcachedClient.php',
	'MemcachedBagOStuff' => __DIR__.'/objectcache/MemcachedBagOStuff.php',
	'MemcachedPeclBagOStuff' => __DIR__.'/objectcache/MemcachedPeclBagOStuff.php',
	'MemcachedPhpBagOStuff' => __DIR__.'/objectcache/MemcachedPhpBagOStuff.php',
	'MultiWriteBagOStuff' => __DIR__.'/objectcache/MultiWriteBagOStuff.php',
	'MWMemcached' => __DIR__.'/objectcache/MemcachedClient.php',
	'ObjectCache' => __DIR__.'/objectcache/ObjectCache.php',
	'ObjectCacheSessionHandler' => __DIR__.'/objectcache/ObjectCacheSessionHandler.php',
	'RedisBagOStuff' => __DIR__.'/objectcache/RedisBagOStuff.php',
	'SqlBagOStuff' => __DIR__.'/objectcache/SqlBagOStuff.php',
	'WinCacheBagOStuff' => __DIR__.'/objectcache/WinCacheBagOStuff.php',
	'XCacheBagOStuff' => __DIR__.'/objectcache/XCacheBagOStuff.php',

	# includes/parser
	'CacheTime' => __DIR__.'/parser/CacheTime.php',
	'CoreParserFunctions' => __DIR__.'/parser/CoreParserFunctions.php',
	'CoreTagHooks' => __DIR__.'/parser/CoreTagHooks.php',
	'DateFormatter' => __DIR__.'/parser/DateFormatter.php',
	'LinkHolderArray' => __DIR__.'/parser/LinkHolderArray.php',
	'MWTidy' => __DIR__.'/parser/Tidy.php',
	'MWTidyWrapper' => __DIR__.'/parser/Tidy.php',
	'PPCustomFrame_DOM' => __DIR__.'/parser/Preprocessor_DOM.php',
	'PPCustomFrame_Hash' => __DIR__.'/parser/Preprocessor_Hash.php',
	'PPDAccum_Hash' => __DIR__.'/parser/Preprocessor_Hash.php',
	'PPDPart' => __DIR__.'/parser/Preprocessor_DOM.php',
	'PPDPart_Hash' => __DIR__.'/parser/Preprocessor_Hash.php',
	'PPDStack' => __DIR__.'/parser/Preprocessor_DOM.php',
	'PPDStackElement' => __DIR__.'/parser/Preprocessor_DOM.php',
	'PPDStackElement_Hash' => __DIR__.'/parser/Preprocessor_Hash.php',
	'PPDStack_Hash' => __DIR__.'/parser/Preprocessor_Hash.php',
	'PPFrame' => __DIR__.'/parser/Preprocessor.php',
	'PPFrame_DOM' => __DIR__.'/parser/Preprocessor_DOM.php',
	'PPFrame_Hash' => __DIR__.'/parser/Preprocessor_Hash.php',
	'PPNode' => __DIR__.'/parser/Preprocessor.php',
	'PPNode_DOM' => __DIR__.'/parser/Preprocessor_DOM.php',
	'PPNode_Hash_Array' => __DIR__.'/parser/Preprocessor_Hash.php',
	'PPNode_Hash_Attr' => __DIR__.'/parser/Preprocessor_Hash.php',
	'PPNode_Hash_Text' => __DIR__.'/parser/Preprocessor_Hash.php',
	'PPNode_Hash_Tree' => __DIR__.'/parser/Preprocessor_Hash.php',
	'PPTemplateFrame_DOM' => __DIR__.'/parser/Preprocessor_DOM.php',
	'PPTemplateFrame_Hash' => __DIR__.'/parser/Preprocessor_Hash.php',
	'Parser' => __DIR__.'/parser/Parser.php',
	'ParserCache' => __DIR__.'/parser/ParserCache.php',
	'ParserOptions' => __DIR__.'/parser/ParserOptions.php',
	'ParserOutput' => __DIR__.'/parser/ParserOutput.php',
	'Parser_DiffTest' => __DIR__.'/parser/Parser_DiffTest.php',
	'Preprocessor' => __DIR__.'/parser/Preprocessor.php',
	'Preprocessor_DOM' => __DIR__.'/parser/Preprocessor_DOM.php',
	'Preprocessor_Hash' => __DIR__.'/parser/Preprocessor_Hash.php',
	'StripState' => __DIR__.'/parser/StripState.php',

	# includes/profiler
	'Profiler' => __DIR__.'/profiler/Profiler.php',
	'ProfilerMwprof' => __DIR__.'/profiler/ProfilerMwprof.php',
	'ProfilerSimple' => __DIR__.'/profiler/ProfilerSimple.php',
	'ProfilerSimpleText' => __DIR__.'/profiler/ProfilerSimpleText.php',
	'ProfilerSimpleTrace' => __DIR__.'/profiler/ProfilerSimpleTrace.php',
	'ProfilerSimpleUDP' => __DIR__.'/profiler/ProfilerSimpleUDP.php',
	'ProfilerStub' => __DIR__.'/profiler/ProfilerStub.php',
	'ProfileSection' => __DIR__.'/profiler/Profiler.php',

	# includes/rcfeed
	'RCFeedEngine' => __DIR__.'/rcfeed/RCFeedEngine.php',
	'RedisPubSubFeedEngine' => __DIR__.'/rcfeed/RedisPubSubFeedEngine.php',
	'UDPRCFeedEngine' => __DIR__.'/rcfeed/UDPRCFeedEngine.php',
	'RCFeedFormatter' => __DIR__.'/rcfeed/RCFeedFormatter.php',
	'IRCColourfulRCFeedFormatter' => __DIR__.'/rcfeed/IRCColourfulRCFeedFormatter.php',
	'JSONRCFeedFormatter' => __DIR__.'/rcfeed/JSONRCFeedFormatter.php',
	'XMLRCFeedFormatter' => __DIR__.'/rcfeed/XMLRCFeedFormatter.php',
	'MachineReadableRCFeedFormatter' => __DIR__.'/rcfeed/MachineReadableRCFeedFormatter.php',

	# includes/resourceloader
	'ResourceLoader' => __DIR__.'/resourceloader/ResourceLoader.php',
	'ResourceLoaderContext' => __DIR__.'/resourceloader/ResourceLoaderContext.php',
	'ResourceLoaderFileModule' => __DIR__.'/resourceloader/ResourceLoaderFileModule.php',
	'ResourceLoaderFilePageModule' => __DIR__.'/resourceloader/ResourceLoaderFilePageModule.php',
	'ResourceLoaderLESSFunctions' => __DIR__.'/resourceloader/ResourceLoaderLESSFunctions.php',
	'ResourceLoaderModule' => __DIR__.'/resourceloader/ResourceLoaderModule.php',
	'ResourceLoaderNoscriptModule' => __DIR__.'/resourceloader/ResourceLoaderNoscriptModule.php',
	'ResourceLoaderSiteModule' => __DIR__.'/resourceloader/ResourceLoaderSiteModule.php',
	'ResourceLoaderStartUpModule' => __DIR__.'/resourceloader/ResourceLoaderStartUpModule.php',
	'ResourceLoaderUserCSSPrefsModule' =>
		'includes/resourceloader/ResourceLoaderUserCSSPrefsModule.php',
	'ResourceLoaderUserGroupsModule' => __DIR__.'/resourceloader/ResourceLoaderUserGroupsModule.php',
	'ResourceLoaderUserModule' => __DIR__.'/resourceloader/ResourceLoaderUserModule.php',
	'ResourceLoaderUserOptionsModule' => __DIR__.'/resourceloader/ResourceLoaderUserOptionsModule.php',
	'ResourceLoaderUserTokensModule' => __DIR__.'/resourceloader/ResourceLoaderUserTokensModule.php',
	'ResourceLoaderLanguageDataModule' =>
		'includes/resourceloader/ResourceLoaderLanguageDataModule.php',
	'ResourceLoaderWikiModule' => __DIR__.'/resourceloader/ResourceLoaderWikiModule.php',

	# includes/revisiondelete
	'RevDel_ArchivedFileItem' => __DIR__.'/revisiondelete/RevisionDelete.php',
	'RevDel_ArchivedFileList' => __DIR__.'/revisiondelete/RevisionDelete.php',
	'RevDel_ArchivedRevisionItem' => __DIR__.'/revisiondelete/RevisionDelete.php',
	'RevDel_ArchiveItem' => __DIR__.'/revisiondelete/RevisionDelete.php',
	'RevDel_ArchiveList' => __DIR__.'/revisiondelete/RevisionDelete.php',
	'RevDel_FileItem' => __DIR__.'/revisiondelete/RevisionDelete.php',
	'RevDel_FileList' => __DIR__.'/revisiondelete/RevisionDelete.php',
	'RevDel_Item' => __DIR__.'/revisiondelete/RevisionDeleteAbstracts.php',
	'RevDel_List' => __DIR__.'/revisiondelete/RevisionDeleteAbstracts.php',
	'RevDel_LogItem' => __DIR__.'/revisiondelete/RevisionDelete.php',
	'RevDel_LogList' => __DIR__.'/revisiondelete/RevisionDelete.php',
	'RevDel_RevisionItem' => __DIR__.'/revisiondelete/RevisionDelete.php',
	'RevDel_RevisionList' => __DIR__.'/revisiondelete/RevisionDelete.php',
	'RevisionDeleter' => __DIR__.'/revisiondelete/RevisionDeleter.php',
	'RevisionDeleteUser' => __DIR__.'/revisiondelete/RevisionDeleteUser.php',

	# includes/search
	'MssqlSearchResultSet' => __DIR__.'/search/SearchMssql.php',
	'MySQLSearchResultSet' => __DIR__.'/search/SearchMySQL.php',
	'PostgresSearchResult' => __DIR__.'/search/SearchPostgres.php',
	'PostgresSearchResultSet' => __DIR__.'/search/SearchPostgres.php',
	'SearchDatabase' => __DIR__.'/search/SearchDatabase.php',
	'SearchEngine' => __DIR__.'/search/SearchEngine.php',
	'SearchEngineDummy' => __DIR__.'/search/SearchEngine.php',
	'SearchHighlighter' => __DIR__.'/search/SearchHighlighter.php',
	'SearchMssql' => __DIR__.'/search/SearchMssql.php',
	'SearchMySQL' => __DIR__.'/search/SearchMySQL.php',
	'SearchNearMatchResultSet' => __DIR__.'/search/SearchResultSet.php',
	'SearchOracle' => __DIR__.'/search/SearchOracle.php',
	'SearchPostgres' => __DIR__.'/search/SearchPostgres.php',
	'SearchResult' => __DIR__.'/search/SearchResult.php',
	'SearchResultSet' => __DIR__.'/search/SearchResultSet.php',
	'SearchResultTooMany' => __DIR__.'/search/SearchEngine.php',
	'SearchSqlite' => __DIR__.'/search/SearchSqlite.php',
	'SqliteSearchResultSet' => __DIR__.'/search/SearchSqlite.php',
	'SqlSearchResultSet' => __DIR__.'/search/SearchResultSet.php',

	# includes/site
	'MediaWikiSite' => __DIR__.'/site/MediaWikiSite.php',
	'Site' => __DIR__.'/site/Site.php',
	'SiteObject' => __DIR__.'/site/Site.php',
	'SiteArray' => __DIR__.'/site/SiteList.php',
	'SiteList' => __DIR__.'/site/SiteList.php',
	'SiteSQLStore' => __DIR__.'/site/SiteSQLStore.php',
	'Sites' => __DIR__.'/site/SiteSQLStore.php',
	'SiteStore' => __DIR__.'/site/SiteStore.php',

	# includes/specialpage
	'ChangesListSpecialPage' => __DIR__.'/specialpage/ChangesListSpecialPage.php',
	'FormSpecialPage' => __DIR__.'/specialpage/FormSpecialPage.php',
	'IncludableSpecialPage' => __DIR__.'/specialpage/IncludableSpecialPage.php',
	'RedirectSpecialArticle' => __DIR__.'/specialpage/RedirectSpecialPage.php',
	'RedirectSpecialPage' => __DIR__.'/specialpage/RedirectSpecialPage.php',
	'SpecialPage' => __DIR__.'/specialpage/SpecialPage.php',
	'SpecialPageFactory' => __DIR__.'/specialpage/SpecialPageFactory.php',
	'SpecialRedirectToSpecial' => __DIR__.'/specialpage/RedirectSpecialPage.php',
	'UnlistedSpecialPage' => __DIR__.'/specialpage/UnlistedSpecialPage.php',

	# includes/specials
	'ActiveUsersPager' => __DIR__.'/specials/SpecialActiveusers.php',
	'AllmessagesTablePager' => __DIR__.'/specials/SpecialAllmessages.php',
	'AncientPagesPage' => __DIR__.'/specials/SpecialAncientpages.php',
	'BlockListPager' => __DIR__.'/specials/SpecialBlockList.php',
	'BrokenRedirectsPage' => __DIR__.'/specials/SpecialBrokenRedirects.php',
	'CategoryPager' => __DIR__.'/specials/SpecialCategories.php',
	'ContribsPager' => __DIR__.'/specials/SpecialContributions.php',
	'DeadendPagesPage' => __DIR__.'/specials/SpecialDeadendpages.php',
	'DeletedContribsPager' => __DIR__.'/specials/SpecialDeletedContributions.php',
	'DeletedContributionsPage' => __DIR__.'/specials/SpecialDeletedContributions.php',
	'DoubleRedirectsPage' => __DIR__.'/specials/SpecialDoubleRedirects.php',
	'EditWatchlistCheckboxSeriesField' => __DIR__.'/specials/SpecialEditWatchlist.php',
	'EditWatchlistNormalHTMLForm' => __DIR__.'/specials/SpecialEditWatchlist.php',
	'EmailConfirmation' => __DIR__.'/specials/SpecialConfirmemail.php',
	'EmailInvalidation' => __DIR__.'/specials/SpecialConfirmemail.php',
	'FewestrevisionsPage' => __DIR__.'/specials/SpecialFewestrevisions.php',
	'FileDuplicateSearchPage' => __DIR__.'/specials/SpecialFileDuplicateSearch.php',
	'HTMLBlockedUsersItemSelect' => __DIR__.'/specials/SpecialBlockList.php',
	'ImageListPager' => __DIR__.'/specials/SpecialListfiles.php',
	'ImportReporter' => __DIR__.'/specials/SpecialImport.php',
	'IPBlockForm' => __DIR__.'/specials/SpecialBlock.php',
	'LinkSearchPage' => __DIR__.'/specials/SpecialLinkSearch.php',
	'ListredirectsPage' => __DIR__.'/specials/SpecialListredirects.php',
	'ListDuplicatedFilesPage' => __DIR__.'/specials/SpecialListDuplicatedFiles.php',
	'LoginForm' => __DIR__.'/specials/SpecialUserlogin.php',
	'LonelyPagesPage' => __DIR__.'/specials/SpecialLonelypages.php',
	'LongPagesPage' => __DIR__.'/specials/SpecialLongpages.php',
	'MergeHistoryPager' => __DIR__.'/specials/SpecialMergeHistory.php',
	'MIMEsearchPage' => __DIR__.'/specials/SpecialMIMEsearch.php',
	'MostcategoriesPage' => __DIR__.'/specials/SpecialMostcategories.php',
	'MostimagesPage' => __DIR__.'/specials/SpecialMostimages.php',
	'MostinterwikisPage' => __DIR__.'/specials/SpecialMostinterwikis.php',
	'MostlinkedCategoriesPage' => __DIR__.'/specials/SpecialMostlinkedcategories.php',
	'MostlinkedPage' => __DIR__.'/specials/SpecialMostlinked.php',
	'MostlinkedTemplatesPage' => __DIR__.'/specials/SpecialMostlinkedtemplates.php',
	'MostrevisionsPage' => __DIR__.'/specials/SpecialMostrevisions.php',
	'MovePageForm' => __DIR__.'/specials/SpecialMovepage.php',
	'NewFilesPager' => __DIR__.'/specials/SpecialNewimages.php',
	'NewPagesPager' => __DIR__.'/specials/SpecialNewpages.php',
	'PageArchive' => __DIR__.'/specials/SpecialUndelete.php',
	'PopularPagesPage' => __DIR__.'/specials/SpecialPopularpages.php',
	'ProtectedPagesPager' => __DIR__.'/specials/SpecialProtectedpages.php',
	'ProtectedTitlesPager' => __DIR__.'/specials/SpecialProtectedtitles.php',
	'RandomPage' => __DIR__.'/specials/SpecialRandompage.php',
	'ShortPagesPage' => __DIR__.'/specials/SpecialShortpages.php',
	'SpecialActiveUsers' => __DIR__.'/specials/SpecialActiveusers.php',
	'SpecialAllmessages' => __DIR__.'/specials/SpecialAllmessages.php',
	'SpecialAllMyUploads' => __DIR__.'/specials/SpecialMyRedirectPages.php',
	'SpecialAllpages' => __DIR__.'/specials/SpecialAllpages.php',
	'SpecialBlankpage' => __DIR__.'/specials/SpecialBlankpage.php',
	'SpecialBlock' => __DIR__.'/specials/SpecialBlock.php',
	'SpecialBlockList' => __DIR__.'/specials/SpecialBlockList.php',
	'SpecialBookSources' => __DIR__.'/specials/SpecialBooksources.php',
	'SpecialCachedPage' => __DIR__.'/specials/SpecialCachedPage.php',
	'SpecialCategories' => __DIR__.'/specials/SpecialCategories.php',
	'SpecialChangeEmail' => __DIR__.'/specials/SpecialChangeEmail.php',
	'SpecialChangePassword' => __DIR__.'/specials/SpecialChangePassword.php',
	'SpecialComparePages' => __DIR__.'/specials/SpecialComparePages.php',
	'SpecialContributions' => __DIR__.'/specials/SpecialContributions.php',
	'SpecialCreateAccount' => __DIR__.'/specials/SpecialCreateAccount.php',
	'SpecialDiff' => __DIR__.'/specials/SpecialDiff.php',
	'SpecialEditWatchlist' => __DIR__.'/specials/SpecialEditWatchlist.php',
	'SpecialEmailUser' => __DIR__.'/specials/SpecialEmailuser.php',
	'SpecialExpandTemplates' => __DIR__.'/specials/SpecialExpandTemplates.php',
	'SpecialExport' => __DIR__.'/specials/SpecialExport.php',
	'SpecialFilepath' => __DIR__.'/specials/SpecialFilepath.php',
	'SpecialImport' => __DIR__.'/specials/SpecialImport.php',
	'SpecialJavaScriptTest' => __DIR__.'/specials/SpecialJavaScriptTest.php',
	'SpecialListAdmins' => __DIR__.'/specials/SpecialListusers.php',
	'SpecialListBots' => __DIR__.'/specials/SpecialListusers.php',
	'SpecialListFiles' => __DIR__.'/specials/SpecialListfiles.php',
	'SpecialListGroupRights' => __DIR__.'/specials/SpecialListgrouprights.php',
	'SpecialListUsers' => __DIR__.'/specials/SpecialListusers.php',
	'SpecialLockdb' => __DIR__.'/specials/SpecialLockdb.php',
	'SpecialLog' => __DIR__.'/specials/SpecialLog.php',
	'SpecialMergeHistory' => __DIR__.'/specials/SpecialMergeHistory.php',
	'SpecialMycontributions' => __DIR__.'/specials/SpecialMyRedirectPages.php',
	'SpecialMypage' => __DIR__.'/specials/SpecialMyRedirectPages.php',
	'SpecialMytalk' => __DIR__.'/specials/SpecialMyRedirectPages.php',
	'SpecialMyuploads' => __DIR__.'/specials/SpecialMyRedirectPages.php',
	'SpecialNewFiles' => __DIR__.'/specials/SpecialNewimages.php',
	'SpecialNewpages' => __DIR__.'/specials/SpecialNewpages.php',
	'SpecialPasswordReset' => __DIR__.'/specials/SpecialPasswordReset.php',
	'SpecialPagesWithProp' => __DIR__.'/specials/SpecialPagesWithProp.php',
	'SpecialPermanentLink' => __DIR__.'/specials/SpecialPermanentLink.php',
	'SpecialPreferences' => __DIR__.'/specials/SpecialPreferences.php',
	'SpecialPrefixindex' => __DIR__.'/specials/SpecialPrefixindex.php',
	'SpecialProtectedpages' => __DIR__.'/specials/SpecialProtectedpages.php',
	'SpecialProtectedtitles' => __DIR__.'/specials/SpecialProtectedtitles.php',
	'SpecialRandomInCategory' => __DIR__.'/specials/SpecialRandomInCategory.php',
	'SpecialRandomredirect' => __DIR__.'/specials/SpecialRandomredirect.php',
	'SpecialRecentChanges' => __DIR__.'/specials/SpecialRecentchanges.php',
	'SpecialRecentChangesLinked' => __DIR__.'/specials/SpecialRecentchangeslinked.php',
	'SpecialRedirect' => __DIR__.'/specials/SpecialRedirect.php',
	'SpecialResetTokens' => __DIR__.'/specials/SpecialResetTokens.php',
	'SpecialRevisionDelete' => __DIR__.'/specials/SpecialRevisiondelete.php',
	'SpecialRunJobs' => __DIR__.'/specials/SpecialRunJobs.php',
	'SpecialSearch' => __DIR__.'/specials/SpecialSearch.php',
	'SpecialSpecialpages' => __DIR__.'/specials/SpecialSpecialpages.php',
	'SpecialStatistics' => __DIR__.'/specials/SpecialStatistics.php',
	'SpecialTags' => __DIR__.'/specials/SpecialTags.php',
	'SpecialTrackingCategories' => __DIR__.'/specials/SpecialTrackingCategories.php',
	'SpecialUnblock' => __DIR__.'/specials/SpecialUnblock.php',
	'SpecialUndelete' => __DIR__.'/specials/SpecialUndelete.php',
	'SpecialUnlockdb' => __DIR__.'/specials/SpecialUnlockdb.php',
	'SpecialUpload' => __DIR__.'/specials/SpecialUpload.php',
	'SpecialUploadStash' => __DIR__.'/specials/SpecialUploadStash.php',
	'SpecialUploadStashTooLargeException' => __DIR__.'/specials/SpecialUploadStash.php',
	'SpecialUserlogout' => __DIR__.'/specials/SpecialUserlogout.php',
	'SpecialVersion' => __DIR__.'/specials/SpecialVersion.php',
	'SpecialWatchlist' => __DIR__.'/specials/SpecialWatchlist.php',
	'SpecialWhatLinksHere' => __DIR__.'/specials/SpecialWhatlinkshere.php',
	'UncategorizedCategoriesPage' => __DIR__.'/specials/SpecialUncategorizedcategories.php',
	'UncategorizedImagesPage' => __DIR__.'/specials/SpecialUncategorizedimages.php',
	'UncategorizedPagesPage' => __DIR__.'/specials/SpecialUncategorizedpages.php',
	'UncategorizedTemplatesPage' => __DIR__.'/specials/SpecialUncategorizedtemplates.php',
	'UnusedCategoriesPage' => __DIR__.'/specials/SpecialUnusedcategories.php',
	'UnusedimagesPage' => __DIR__.'/specials/SpecialUnusedimages.php',
	'UnusedtemplatesPage' => __DIR__.'/specials/SpecialUnusedtemplates.php',
	'UnwatchedpagesPage' => __DIR__.'/specials/SpecialUnwatchedpages.php',
	'UploadChunkFileException' => __DIR__.'/upload/UploadFromChunks.php',
	'UploadChunkZeroLengthFileException' => __DIR__.'/upload/UploadFromChunks.php',
	'UploadChunkVerificationException' => __DIR__.'/upload/UploadFromChunks.php',
	'UploadForm' => __DIR__.'/specials/SpecialUpload.php',
	'UploadSourceField' => __DIR__.'/specials/SpecialUpload.php',
	'UserrightsPage' => __DIR__.'/specials/SpecialUserrights.php',
	'UsersPager' => __DIR__.'/specials/SpecialListusers.php',
	'WantedCategoriesPage' => __DIR__.'/specials/SpecialWantedcategories.php',
	'WantedFilesPage' => __DIR__.'/specials/SpecialWantedfiles.php',
	'WantedPagesPage' => __DIR__.'/specials/SpecialWantedpages.php',
	'WantedTemplatesPage' => __DIR__.'/specials/SpecialWantedtemplates.php',
	'WatchlistEditor' => __DIR__.'/specials/SpecialEditWatchlist.php',
	'WithoutInterwikiPage' => __DIR__.'/specials/SpecialWithoutinterwiki.php',

	# includes/templates
	'UserloginTemplate' => __DIR__.'/templates/Userlogin.php',
	'UsercreateTemplate' => __DIR__.'/templates/Usercreate.php',

	# includes/title
	'PageLinkRenderer' => __DIR__.'/title/PageLinkRenderer.php',
	'TitleFormatter' => __DIR__.'/title/TitleFormatter.php',
	'TitleParser' => __DIR__.'/title/TitleParser.php',
	'TitleValue' => __DIR__.'/title/TitleValue.php',
	'MalformedTitleException' => __DIR__.'/title/MalformedTitleException.php',
	'MediaWikiPageLinkRenderer' => __DIR__.'/title/MediaWikiPageLinkRenderer.php',
	'MediaWikiTitleCodec' => __DIR__.'/title/MediaWikiTitleCodec.php',

	# includes/upload
	'UploadBase' => __DIR__.'/upload/UploadBase.php',
	'UploadFromFile' => __DIR__.'/upload/UploadFromFile.php',
	'UploadFromChunks' => __DIR__.'/upload/UploadFromChunks.php',
	'UploadFromStash' => __DIR__.'/upload/UploadFromStash.php',
	'UploadFromUrl' => __DIR__.'/upload/UploadFromUrl.php',
	'UploadStash' => __DIR__.'/upload/UploadStash.php',
	'UploadStashBadPathException' => __DIR__.'/upload/UploadStash.php',
	'UploadStashException' => __DIR__.'/upload/UploadStash.php',
	'UploadStashFile' => __DIR__.'/upload/UploadStash.php',
	'UploadStashFileException' => __DIR__.'/upload/UploadStash.php',
	'UploadStashFileNotFoundException' => __DIR__.'/upload/UploadStash.php',
	'UploadStashNotAvailableException' => __DIR__.'/upload/UploadStash.php',
	'UploadStashZeroLengthFileException' => __DIR__.'/upload/UploadStash.php',
	'UploadStashNotLoggedInException' => __DIR__.'/upload/UploadStash.php',
	'UploadStashWrongOwnerException' => __DIR__.'/upload/UploadStash.php',
	'UploadStashNoSuchKeyException' => __DIR__.'/upload/UploadStash.php',

	# includes/utils
	'ArrayUtils' => __DIR__.'/utils/ArrayUtils.php',
	'CdbException' => __DIR__.'/utils/Cdb.php',
	'CdbFunctions' => __DIR__.'/utils/CdbPHP.php',
	'CdbReader' => __DIR__.'/utils/Cdb.php',
	'CdbReaderDBA' => __DIR__.'/utils/CdbDBA.php',
	'CdbReaderPHP' => __DIR__.'/utils/CdbPHP.php',
	'CdbWriter' => __DIR__.'/utils/Cdb.php',
	'CdbWriterDBA' => __DIR__.'/utils/CdbDBA.php',
	'CdbWriterPHP' => __DIR__.'/utils/CdbPHP.php',
	'ConfEditor' => __DIR__.'/utils/ConfEditor.php',
	'ConfEditorParseError' => __DIR__.'/utils/ConfEditor.php',
	'ConfEditorToken' => __DIR__.'/utils/ConfEditor.php',
	//'DoubleReplacer' => __DIR__.'/utils/StringUtils.php',
	//'ExplodeIterator' => __DIR__.'/utils/StringUtils.php',
	//'HashtableReplacer' => __DIR__.'/utils/StringUtils.php',
	'IP' => __DIR__.'/utils/IP.php',
	'MWCryptRand' => __DIR__.'/utils/MWCryptRand.php',
	'MWFunction' => __DIR__.'/utils/MWFunction.php',
	//'RegexlikeReplacer' => __DIR__.'/utils/StringUtils.php',
	//'ReplacementArray' => __DIR__.'/utils/StringUtils.php',
	//'Replacer' => __DIR__.'/utils/StringUtils.php',
	//'StringUtils' => __DIR__.'/utils/StringUtils.php',
	'UIDGenerator' => __DIR__.'/utils/UIDGenerator.php',
	'ZipDirectoryReader' => __DIR__.'/utils/ZipDirectoryReader.php',
	'ZipDirectoryReaderError' => __DIR__.'/utils/ZipDirectoryReader.php',

	# languages
	'ConverterRule' => 'languages/ConverterRule.php',
	//'FakeConverter' => 'languages/Language.php',
	'Language' => 'languages/Language.php',
	'LanguageConverter' => 'languages/LanguageConverter.php',
	'CLDRPluralRuleConverter' => 'languages/utils/CLDRPluralRuleConverter.php',
	'CLDRPluralRuleConverter_Expression' => 'languages/utils/CLDRPluralRuleConverter_Expression.php',
	'CLDRPluralRuleConverter_Fragment' => 'languages/utils/CLDRPluralRuleConverter_Fragment.php',
	'CLDRPluralRuleConverter_Operator' => 'languages/utils/CLDRPluralRuleConverter_Operator.php',
	'CLDRPluralRuleEvaluator' => 'languages/utils/CLDRPluralRuleEvaluator.php',
	'CLDRPluralRuleEvaluator_Range' => 'languages/utils/CLDRPluralRuleEvaluator_Range.php',
	'CLDRPluralRuleError' => 'languages/utils/CLDRPluralRuleError.php',

	# maintenance
	'BackupDumper' => 'maintenance/backup.inc',
	'ConvertLinks' => 'maintenance/convertLinks.php',
	'DeleteArchivedFilesImplementation' => 'maintenance/deleteArchivedFiles.inc',
	'DeleteArchivedRevisionsImplementation' => 'maintenance/deleteArchivedRevisions.inc',
	'DeleteDefaultMessages' => 'maintenance/deleteDefaultMessages.php',
	'DumpDBZip2Output' => 'maintenance/backup.inc',
	'ExportProgressFilter' => 'maintenance/backup.inc',
	'FakeMaintenance' => 'maintenance/Maintenance.php',
	'FixExtLinksProtocolRelative' => 'maintenance/fixExtLinksProtocolRelative.php',
	'LoggedUpdateMaintenance' => 'maintenance/Maintenance.php',
	'Maintenance' => 'maintenance/Maintenance.php',
	'PopulateCategory' => 'maintenance/populateCategory.php',
	'PopulateImageSha1' => 'maintenance/populateImageSha1.php',
	'PopulateFilearchiveSha1' => 'maintenance/populateFilearchiveSha1.php',
	'PopulateLogSearch' => 'maintenance/populateLogSearch.php',
	'PopulateLogUsertext' => 'maintenance/populateLogUsertext.php',
	'PopulateParentId' => 'maintenance/populateParentId.php',
	'PopulateRevisionLength' => 'maintenance/populateRevisionLength.php',
	'PopulateRevisionSha1' => 'maintenance/populateRevisionSha1.php',
	'RefreshLinks' => 'maintenance/refreshLinks.php',
	'SevenZipStream' => 'maintenance/7zip.inc',
	'Sqlite' => 'maintenance/sqlite.inc',
	'UpdateCollation' => 'maintenance/updateCollation.php',
	'UpdateRestrictions' => 'maintenance/updateRestrictions.php',
	'UserDupes' => 'maintenance/userDupes.inc',

	# maintenance/language
	'CsvStatsOutput' => 'maintenance/language/StatOutputs.php',
	'ExtensionLanguages' => 'maintenance/language/languages.inc',
	'Languages' => 'maintenance/language/languages.inc',
	'MessageWriter' => 'maintenance/language/writeMessagesArray.inc',
	'StatsOutput' => 'maintenance/language/StatOutputs.php',
	'TextStatsOutput' => 'maintenance/language/StatOutputs.php',
	'WikiStatsOutput' => 'maintenance/language/StatOutputs.php',

	# maintenance/term
	'AnsiTermColorer' => 'maintenance/term/MWTerm.php',
	'DummyTermColorer' => 'maintenance/term/MWTerm.php',

	# mw-config
	'InstallerOverrides' => 'mw-config/overrides.php',
	'MyLocalSettingsGenerator' => 'mw-config/overrides.php',

	# skins
	'CologneBlueTemplate' => 'skins/CologneBlue.php',
	'ModernTemplate' => 'skins/Modern.php',
	'MonoBookTemplate' => 'skins/MonoBook.php',
	'SkinCologneBlue' => 'skins/CologneBlue.php',
	'SkinModern' => 'skins/Modern.php',
	'SkinMonoBook' => 'skins/MonoBook.php',
	'SkinVector' => 'skins/Vector.php',
	'VectorTemplate' => 'skins/Vector.php',
);

class AutoLoader {
	static protected $autoloadLocalClassesLower = null;

	/**
	 * autoload - take a class name and attempt to load it
	 *
	 * @param string $className name of class we're looking for.
	 */
	static function autoload( $className ) {
		global $wgAutoloadClasses, $wgAutoloadLocalClasses,
			$wgAutoloadAttemptLowercase;

		// Workaround for PHP bug <https://bugs.php.net/bug.php?id=49143> (5.3.2. is broken, it's
		// fixed in 5.3.6). Strip leading backslashes from class names. When namespaces are used,
		// leading backslashes are used to indicate the top-level namespace, e.g. \foo\Bar. When
		// used like this in the code, the leading backslash isn't passed to the auto-loader
		// ($className would be 'foo\Bar'). However, if a class is accessed using a string instead
		// of a class literal (e.g. $class = '\foo\Bar'; new $class()), then some versions of PHP
		// do not strip the leading backlash in this case, causing autoloading to fail.
		$className = ltrim( $className, '\\' );

		$filename = false;

		if ( isset( $wgAutoloadLocalClasses[$className] ) ) {
			$filename = $wgAutoloadLocalClasses[$className];
		} elseif ( isset( $wgAutoloadClasses[$className] ) ) {
			$filename = $wgAutoloadClasses[$className];
		} elseif ( $wgAutoloadAttemptLowercase ) {
			/*
			 * Try a different capitalisation.
			 *
			 * PHP 4 objects are always serialized with the classname coerced to lowercase,
			 * and we are plagued with several legacy uses created by MediaWiki < 1.5, see
			 * https://wikitech.wikimedia.org/wiki/Text_storage_data
			 */
			$lowerClass = strtolower( $className );

			if ( self::$autoloadLocalClassesLower === null ) {
				self::$autoloadLocalClassesLower = array_change_key_case( $wgAutoloadLocalClasses, CASE_LOWER );
			}

			if ( isset( self::$autoloadLocalClassesLower[$lowerClass] ) ) {
				if ( function_exists( 'wfDebugLog' ) ) {
					wfDebugLog( 'autoloader', "Class {$className} was loaded using incorrect case" );
				}
				$filename = self::$autoloadLocalClassesLower[$lowerClass];
			}
		}

		if ( !$filename ) {
			// Class not found; let the next autoloader try to find it
			return;
		}

		// Make an absolute path, this improves performance by avoiding some stat calls
		if ( substr( $filename, 0, 1 ) != '/' && substr( $filename, 1, 1 ) != ':' ) {
			global $IP;
			$filename = "$IP/$filename";
		}

		require $filename;
	}

	/**
	 * Force a class to be run through the autoloader, helpful for things like
	 * Sanitizer that have define()s outside of their class definition. Of course
	 * this wouldn't be necessary if everything in MediaWiki was class-based. Sigh.
	 *
	 * @param $class string
	 * @return Boolean Return the results of class_exists() so we know if we were successful
	 */
	static function loadClass( $class ) {
		return class_exists( $class );
	}

	/**
	 * Method to clear the protected class property $autoloadLocalClassesLower.
	 * Used in tests.
	 */
	static function resetAutoloadLocalClassesLower() {
		self::$autoloadLocalClassesLower = null;
	}
}

spl_autoload_register( array( 'AutoLoader', 'autoload' ) );
